export default {
  'pages.layouts.userLayout.title': '成都赛美斯医疗技术有限公司',
  'pages.login.title': '运维管理系统',
  'pages.login.account.remark': '邮箱',
  'pages.login.account.remark2': '用户名',
  'pages.login.accountLogin.tab': '账号登陆',
  'pages.login.accountLogin.errorMessage': '错误的用户名和密码(admin/ant.design)',
  'pages.login.failure': '登录失败，请重试！',
  'pages.login.success': '登录成功！',
  'pages.login.username.placeholder': '用户名: admin or user',
  'pages.login.username.required': '用户名是必填项！',
  'pages.login.password.placeholder': '密码',
  'pages.login.password.required': '密码是必填项！',
  'pages.login.phoneLogin.tab': '手机号登录',
  'pages.login.phoneLogin.errorMessage': '验证码错误',
  'pages.login.phoneNumber.placeholder': '请输入手机号！',
  'pages.login.phoneNumber.required': '手机号是必填项！',
  'pages.login.phoneNumber.invalid': '不合法的手机号！',
  'pages.login.captcha.placeholder': '请输入验证码！',
  'pages.login.captcha.required': '验证码是必填项！',
  'pages.login.phoneLogin.getVerificationCode': '获取验证码',
  'pages.getCaptchaSecondText': '秒后重新获取',
  'pages.login.rememberMe': '记住用户名',
  'pages.login.forgotPassword': '忘记密码 ?',
  'pages.login.submit': '登录',
  'pages.login.loginWith': '其他登录方式 :',
  'pages.login.registerAccount': '注册账户',
  'pages.welcome.advancedComponent': '高级表格',
  'pages.welcome.link': '欢迎使用',
  'pages.welcome.advancedLayout': '高级布局',
  'pages.welcome.alertMessage': '更快更强的重型组件，已经发布。',
  'pages.admin.subPage.title': ' 这个页面只有 admin 权限才能查看',
  'pages.admin.subPage.alertMessage': 'umi ui 现已发布，欢迎使用 npm run ui 启动体验。',
  'pages.searchTable.createForm.newRule': '新建规则',
  'pages.searchTable.updateForm.ruleConfig': '规则配置',
  'pages.searchTable.updateForm.basicConfig': '基本信息',
  'pages.searchTable.updateForm.ruleName.nameLabel': '规则名称',
  'pages.searchTable.updateForm.ruleName.nameRules': '请输入规则名称！',
  'pages.searchTable.updateForm.ruleDesc.descLabel': '规则描述',
  'pages.searchTable.updateForm.ruleDesc.descPlaceholder': '请输入至少五个字符',
  'pages.searchTable.updateForm.ruleDesc.descRules': '请输入至少五个字符的规则描述！',
  'pages.searchTable.updateForm.ruleProps.title': '配置规则属性',
  'pages.searchTable.updateForm.object': '监控对象',
  'pages.searchTable.updateForm.ruleProps.templateLabel': '规则模板',
  'pages.searchTable.updateForm.ruleProps.typeLabel': '规则类型',
  'pages.searchTable.updateForm.schedulingPeriod.title': '设定调度周期',
  'pages.searchTable.updateForm.schedulingPeriod.timeLabel': '开始时间',
  'pages.searchTable.updateForm.schedulingPeriod.timeRules': '请选择开始时间！',
  'pages.searchTable.titleDesc': '描述',
  'pages.searchTable.ruleName': '规则名称为必填项',
  'pages.searchTable.titleCallNo': '服务调用次数',
  'pages.searchTable.titleStatus': '状态',
  'pages.searchTable.nameStatus.default': '关闭',
  'pages.searchTable.nameStatus.running': '运行中',
  'pages.searchTable.nameStatus.online': '已上线',
  'pages.searchTable.nameStatus.abnormal': '异常',
  'pages.searchTable.titleUpdatedAt': '上次调度时间',
  'pages.searchTable.exception': '请输入异常原因！',
  'pages.searchTable.titleOption': '操作',
  'pages.searchTable.config': '配置',
  'pages.searchTable.subscribeAlert': '订阅警报',
  'pages.searchTable.title': '查询表格',
  'pages.searchTable.new': '新建',
  'pages.searchTable.chosen': '已选择',
  'pages.searchTable.item': '项',
  'pages.searchTable.totalServiceCalls': '服务调用次数总计',
  'pages.searchTable.tenThousand': '万',
  'pages.searchTable.batchDeletion': '批量删除',
  'pages.searchTable.batchApproval': '批量审批',
  'pages.searchTable.max': '达到最大数值无法添加！',
  //#region 通用
  'pages.system-name': '运维管理系统',
  'pages.type': '类型',
  'pages.status': '状态',
  'pages.operate': '操作',
  'pages.import': '导入',
  'pages.export': '导出',
  'pages.edit': '编辑',
  'pages.detail': '详情',
  'pages.log': '日志',
  'pages.delete': '删除',
  'pages.restore': '恢复',
  'pages.confirm.title': '提示',
  'pages.more': '更多',
  'pages.not.changed': '数据未更改',
  'pages.published': '已发布',
  'pages.unPublish': '待发布',
  'pages.publish': '发布',
  'pages.creator': '创建人',
  'pages.createTime': '创建时间',
  'pages.seq': '序号',
  'pages.save': '保存',
  //#endregion

  //#region 首页 工作台
  'pages.workbench.systemModel': '系统模块',
  'pages.workbench.eService': 'eService',
  'pages.workbench.eLearning': 'eLearning',
  'pages.workbench.allSystem': '全部系统',
  'pages.workbench.todos': '待办事项',
  'pages.workbench.note': '便签',
  //#endregion
  // #region account 基本信息/安全设置
  'pages.account.securitySettings': '安全设置',
  'pages.account.loginPassword': '登录密码',
  'pages.account.loginPassword.tip': '密码必须由字母、数字、特殊字符组成，且长度必须大于8位',
  'pages.account.email': '邮箱账号',
  'pages.account.logout': '退出登录',
  'pages.account.change': '修改',

  'pages.account.currentPassword.level': '当前密码等级：',
  // #endregion

  // #region account 忘记密码
  'pages.forgot.next': '下一步',
  'pages.forgot.tip.left': '临时验证码已发送至您的邮箱',
  'pages.forgot.tip.right': '请注意查收',
  'pages.forgot.resent': '重新获取',
  'pages.forgot.pwdRule': '密码规则：密码必须由字母、数字、特殊字符组成，且长度必须大于8位',
  'pages.forgot.success': '密码重置成功!请使用新密码登陆',
  'pages.forgot.login': '立即登录',
  'pages.forgot.login.icon': '登录',
  'pages.forgot.step1': '获取临时密码',
  'pages.forgot.step2': '密码重置',
  'pages.forgot.step3': '重置成功',
  // #endregion

  //#region 用户管理
  'pages.usermanage.userID': '用户ID',
  'pages.usermanage.edit.pwd': '密码修改',
  'pages.usermanage.new.pwd': '新密码',
  'pages.usermanage.new.pwd.rule': '请输入新密码',
  'pages.usermanage.new1.pwd': '确认新密码',
  'pages.usermanage.new1.pwd.rule': '请输入确认新密码',
  'pages.usermanage.name': '姓名',
  'pages.usermanage.email': '邮箱',
  'pages.usermanage.email.tip': '邮箱是唯一的key',
  'pages.usermanage.groupPosition': '组织/职位',
  'pages.usermanage.deleteTime': '删除时间',
  'pages.usermanage.operator': '操作者',
  'pages.usermanage.batchInvalidate': '批量无效',
  'pages.usermanage.batchValidate': '批量有效',
  'pages.usermanage.invalidate': '无效',
  'pages.usermanage.validate': '有效',
  'pages.usermanage.status.formal': '正式',
  'pages.usermanage.status.internship': '实习',
  'pages.usermanage.addUsers': '新增用户',
  'pages.usermanage.editUsers': '编辑用户',
  'pages.usermanage.deletableUsers': '可删除用户',
  'pages.usermanage.recycleBin': '回收站',
  'pages.usermanage.maintainOrganization': '组织维护',
  'pages.usermanage.resetPassword': '重置密码',
  'pages.usermanage.resetPassword.success': '重置密码成功!',
  'pages.usermanage.resetPassword.false': '重置密码失败!',
  'pages.usermanage.invalidate.confirm': '您确定无效该用户吗？',
  'pages.usermanage.invalidate.success': '无效成功!',
  'pages.usermanage.validate.success': '有效成功!',
  'pages.usermanage.confirmBatchValidate': '您确定批量有效当前选中行吗？',
  'pages.usermanage.confirmBatchInvalidate': '您确定批量无效当前选中行吗？',
  'pages.usermanage.confirmBatchDelete': '您确定批量删除当前选中行吗？',
  'pages.usermanage.confirmBatchRestore': '您确定批量恢复当前选中行吗？',
  'pages.usermanage.batchInvalidate.success': '批量无效成功!',
  'pages.usermanage.batchValidate.success': '批量有效成功!',
  'pages.usermanage.batch.tip': '批量操作数据至少选择2条!',
  'pages.usermanage.batchRestore': '批量恢复',
  'pages.usermanage.batchRestore.success': '批量恢复成功!',
  'pages.usermanage.restore.success': '恢复成功',
  'pages.usermanage.restore.false': '恢复失败',
  'pages.usermanage.add.success': '添加成功',
  'pages.usermanage.add.false': '添加失败',
  'pages.usermanage.del.success': '删除成功',
  'pages.usermanage.del.false': '删除失败',
  'pages.usermanage.edit.success': '修改成功',
  'pages.usermanage.edit.false': '修改失败',
  'pages.usermanage.export.success': '导出成功',
  'pages.usermanage.export.false': '导出失败',
  'pages.usermanage.addPosition': '添加职位',
  'pages.usermanage.addSub': '添加子组织',
  'pages.usermanage.editSub': '修改名称',
  'pages.usermanage.delSub': '删除',
  'pages.usermanage.del': '批量删除',
  'pages.usermanage.batchDel.success': '批量删除成功',
  'pages.usermanage.table.index': '序号',
  'pages.usermanage.table.positionName': '职位名称',
  'pages.usermanage.table.organization': '组织',
  'pages.usermanage.table.updateTime': '最后修改时间',
  'pages.usermanage.table.update': '修改信息',
  'pages.usermanage.left.title': '组织架构',
  'pages.usermanage.modaltitle1.left': '用户管理-',
  'pages.usermanage.modaltitle1.right': '-添加职位',
  'pages.usermanage.modaltitle2': '用户管理-组织维护-修改职位信息',
  'pages.usermanage.modaltitle.left': '组织维护-',
  'pages.usermanage.modaltitle.right': '-添加子组织',
  'pages.usermanage.modaltitle.All': '组织维护-添加组织',
  'pages.usermanage.modaltitle.right2': '-修改信息',
  'pages.usermanage.from.organizationCode': '组织编号',
  'pages.usermanage.from.organizationName': '组织名称',
  'pages.usermanage.from.positionName': '职位名称',
  'pages.usermanage.from.placeholder': '请输入',
  'pages.usermanage.from.rule': '请输入组织编号！',
  'pages.usermanage.from.rule1': '请输入组织名称！',
  'pages.usermanage.from.rule2': '请输入职位名称！',
  'pages.usermanage.log.opero': '操作者',
  'pages.usermanage.log.operoTime': '变更时间',
  'pages.usermanage.log.sendTime': '最近发送时间',
  'pages.usermanage.log.operoObj': '变更对象',
  'pages.usermanage.log.action': '动作',
  'pages.usermanage.log.oldVal': '原值',
  'pages.usermanage.log.newVal': '新值',
  'pages.usermanage.log': '操作日志',
  'pages.usermanage.Email_log': '邮件日志',
  'pages.usermanage.Email_title': '主题',
  'pages.usermanage.resend.Email': '重新发送',
  'pages.usermanage.delOrganization.waring': '存在子组织，无法删除!',
  'pages.usermanage.resetPassword.confirm': '您确定重置密码吗?',
  'pages.usermanage.emaile.error': '邮箱格式不正确',
  'pages.usermanage.label.phone': '联系电话',
  'pages.usermanage.phone.error': '手机号格式不正确',
  'pages.usermanage.item.invalid': '是否要使项目无效？',
  'pages.usermanage.invalid.reason': '无效原因',
  'pages.usermanage.module.mark': '模块负责人-工单-痕迹',
  'pages.usermanage.item.restore': '您是否还原此项目',
  'pages.usermanage.del.user': '您确定要删除此用户吗？',
  'pages.usermanage.user.list': '用户列表',
  //#endregion

  //#region 权限管理
  'pages.power.module.name': '模块名称',
  'pages.power.master.administrator': '主管理员',
  'pages.power.sub.administrator': '子管理员',

  //#endregion

  //#region 系统参数
  'pages.sysParams.port.STMP':'STMP服务端口号',
  'pages.sysParams.port.STMP.tip': '请输入SMTP服务端口号',
  'pages.sysParams.port.STMP.extra':'提示:服务器格式以stmp/pop/poo3开头数字或字母1-9位，以2-8位字母结尾stmp.bmclinsys.com',
  'pages.sysParams.port.portnumber': '端口号',
  'pages.sysParams.port.portnumber.tip':'请输入端口号',
  'pages.sysParams.port.SSL': 'SSL',
  'pages.sysParams.port.SSL.tip': '请输入SSL',
  'pages.sysParams.port.account': '账号',
  'pages.sysParams.port.account.tip': '请输入账号',
  'pages.sysParams.port.account.extra': '提示:邮件发送人账号',
  'pages.sysParams.port.password':'密码',
  'pages.sysParams.port.password.tip': '请输入密码',
  'pages.sysParams.port.password.extra': '提示:邮件发送人密码',
  'pages.sysParams.port.name': '名称',
  'pages.sysParams.port.name.tip': '请输入名称',
  'pages.sysParams.port.name.extra': '提示:邮件发送人名称',
  'pages.sysParams.port.test': '邮件测试',
  'pages.sysParams.port.sendEmail': '发送邮件',


  
  //#endregion

  // #region

  // #endregion



  //#region  工单管理
  'pages.eservice.invalidTemplate': '无效模板',
  'pages.eservice.maintainType': '维护类型',
  'pages.eservice.addTemplate': '新增模板',
  'pages.eservice.templateID': '工单模板ID',
  'pages.eservice.templateName': '工单模板名称',
  'pages.eservice.publishStatus': '发布状态',
  'pages.eservice.workOrderType': '工单类型',
  'pages.eservice.workOrderProperty': '工单属性',
  'pages.eservice.plat': '平台',
  'pages.eservice.project': '项目',
  'pages.eservice.setTemplate': '模板设置',
  'pages.eservice.invalidType': '无效类型',
  'pages.eservice.addType': '新增类型',
  'pages.eservice.workOrderTypeList': '工单类型列表',
  'pages.eservice.invalidWorkOrderTypeList': '无效工单类型列表',
  'pages.eservice.workOrderTypeID': '工单类型ID',
  'pages.eservice.workOrderTypeName': '工单类型名称',
  'pages.eservice.workOrderTypeDesc': '工单类型描述',
  'pages.eservice.workOrderNumber': '工单数量',
  'pages.eservice.viewTemplate': '查看模板',
  'pages.eservice.sureInvalid': '确定要无效吗?',
  'pages.eservice.sureRecovery': '确定要恢复吗?',
  'pages.eservice.tempList': '工单模板清单',

  //#endregion
};
